# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 19:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gamemode',
            field=models.CharField(choices=[('UHC', 'Ultra Hardcore'), ('SUR', 'Survival')], default='UHC', max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.CharField(choices=[('UHC1', 'Ultra Hardcore Server 1'), ('UHC2', 'Ultra Hardcore Server 2')], default='UHC1', max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='team_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 7, 27, 15, 7, 15, 294501)),
        ),
    ]
