# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 19:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0002_auto_20160727_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='region',
            new_name='server',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 7, 27, 15, 7, 48, 514728)),
        ),
    ]
